/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/El3elrcSTXS
 */
import Link from "next/link"

export function AboutUs() {
  return (
    <section key="1" className="w-full py-12 md:py-24 lg:py-32">
    
        <div className="grid gap-6 lg:grid-cols-1 xl:grid-cols-1">
          <section className="flex flex-col lg:flex-row items-center space-y-4 lg:space-y-0 lg:space-x-4 w-full">
            
            <div>
            <h3 className="text-xl font-bold">Our Company</h3>
              <p className="text-gray-500 justify-text-left md:text-base dark:text-gray-400">
                Welcome to your destination for professional lawn care and landscape design services. As a newly established business, we are dedicated to providing top-quality solutions to meet our clients outdoor maintenance and design needs.
              </p>

              <br></br>
              
              <h2 className="text-gray-500 justify-text-left md:text-base dark:text-gray-400">
              <b className="text-gray-300"> We specialize in two core areas:</b><br></br><br></br>
              </h2> 
              <p className="text-gray-500 justify-text-left md:text-base dark:text-gray-400">
              <b className="text-gray-300">Lawn Care:</b> Our team is passionate about transforming ordinary lawns into verdant, healthy landscapes that enhance the beauty and value of your property. From regular mowing and edging to fertilization and weed control, we offer comprehensive lawn care services to keep your lawn looking its best year-round.
              </p>
              <br></br>
              <p className="text-gray-500 justify-text-left md:text-base dark:text-gray-400">
                <b className="text-gray-300">Budget-Friendly Landscape Design:</b> We believe that every outdoor space has the potential to be beautiful, regardless of budget constraints. Our small-budget landscape design services are tailored to meet your aesthetic preferences and financial considerations, providing creative solutions to maximize the visual appeal and functionality of your outdoor environment.
              </p>
            
            </div>
          </section>
        
        <div className="flex justify-center mt-12">
          <Link
            className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
            href="./Contact"
            >

            Get a Free Quote
          </Link>
        </div>
      </div>
    </section>
  )
}


function TractorIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 4h9l1 7" />
      <path d="M4 11V4" />
      <path d="M8 10V4" />
      <path d="M18 5c-.6 0-1 .4-1 1v5.6" />
      <path d="m10 11 .9c.6 0 .9.5.8 1.1l-.8 5h-1" />
      <circle cx="7" cy="15" r=".5" />
      <circle cx="7" cy="15" r="5" />
      <path d="M16 18h-5" />
      <circle cx="18" cy="18" r="2" />
    </svg>
  )
}


function FlowerIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 7.5a4.5 4.5 0 1 4.5M12 7.5A4.5 7.5 12M12 7.5V9m-4.5 3a4.5 4.5M7.5 12H9m7.5 0a4.5 1-4.5 4.5m4.5-4.5H15m-3 4.5V15" />
      <circle cx="12" cy="12" r="3" />
      <path d="m8 16 1.5-1.5" />
      <path d="M14.5 9.5 16 8" />
      <path d="m8 8 1.5" />
      <path d="M14.5 14.5 16" />
    </svg>
  )
}


function CropIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 2v14a2 2 0 2h14" />
      <path d="M18 22V8a2 2 0 0-2-2H2" />
    </svg>
  )
}
