/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BIWoCiTgqeg
 */
import Link from "next/link"

export function ServicesPage() {
  return (
    <main className="w-full py-6 xs:py-2 s:py-4 md:py-8 lg:py-10">
      <section className="container px-2 md:px-4 py-6 xs:py-2 s:py-4 md:py-8 lg:py-10">
        <div className="flex flex-col items-left space-y-2 w-full">
          <TractorIcon className="h-8 w-8" />
          <h3 className="text-xl font-bold">Lawn Care is our Specialty</h3>
          <p className="text-gray-500 text-sm dark:text-gray-400">
          <b className="text-gray-300">Lawn Mowing & Edging:</b><br></br> We use motorized battery powered equipment for fine tuned accuracy. Attention to detail for a polished finish is our competitive advantage.
          <br></br>
          <b className="text-gray-300">Fertilization and Weed Control:</b><br></br>  Achieve a healthy, vibrant lawn with our customized fertilization programs designed to promote lush growth while effectively controlling weeds.
          <br></br>
          <b className="text-gray-300">Aeration, Dethatching and Re-Seeding:</b><br></br>  Improve soil health and promote strong root growth with our aeration and re-seeding services alleviating soil compaction and encourage healthy turf.
          <br></br>
          <b className="text-gray-300">Lawn Pest and Disease Management:</b><br></br>  Protect your lawn from pests and diseases with our targeted treatment plans, addreessing common lawn issues.
          <br></br>
          <b className="text-gray-300">Seasonal Clean-Up:</b><br></br>  From spring clean-ups to fall leaf removal. We tidy your lawn and garden back to its best life.
          </p>
          
        </div>
      </section>
      <section className="container px-2 md:px-4 py-6 xs:py-2 s:py-4 md:py-8 lg:py-10">
        <div className="flex flex-col items-left  space-y-2 w-full">
          <FlowerIcon className="h-8 w-8" />
          <h3 className="text-xl font-bold">Garden Design</h3>
          <p className="text-gray-500 justify-center mx-auto text-sm dark:text-gray-400">
          From selecting plants of your preference to finishing touches like low-voltage lighting. We can build your beautiful and functional garden space tailored to your needs. We have the tools and know-how to create a landscape that augments your home day and night.
          We are currently focused on transforming landscapes and gardens in the range of $500 to $3000. For budgets exceeding $3000, please contact us and we will refer you to a designer landscaping firm. </p>
          
        </div>
      </section>
      <section className="container px-2 md:px-4 py-6 xs:py-2 s:py-4 md:py-8 lg:py-10">
        <div className="flex flex-col items-left space-y-2 w-full">
          <CropIcon className="h-8 w-8" />
          <h3 className="text-xl font-bold">Irrigation System Installation</h3>
          <p className="text-gray-500 text-sm dark:text-gray-400">
            We design and install efficient irrigation systems to ensure your plants get the right amount of water.
          </p>
          
        </div>
      </section>
      <div className="fixed right-4 bottom-4 md:right-8 md:bottom-8">
        <Link
          className="inline-flex h-12 items-center justify-center rounded-md bg-gray-900 px-6 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
          href="./Contact"
        >
          Get a Free Quote
        </Link>
      </div>
    </main>
  )
}


function TractorIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 4h9l1 7" />
      <path d="M4 11V4" />
      <path d="M8 10V4" />
      <path d="M18 5c-.6 0-1 .4-1 1v5.6" />
      <path d="m10 11 .9c.6 0 .9.5.8 1.1l-.8 5h-1" />
      <circle cx="7" cy="15" r=".5" />
      <circle cx="7" cy="15" r="5" />
      <path d="M16 18h-5" />
      <circle cx="18" cy="18" r="2" />
    </svg>
  )
}


function FlowerIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 7.5a4.5 4.5 0 1 4.5M12 7.5A4.5 7.5 12M12 7.5V9m-4.5 3a4.5 4.5M7.5 12H9m7.5 0a4.5 1-4.5 4.5m4.5-4.5H15m-3 4.5V15" />
      <circle cx="12" cy="12" r="3" />
      <path d="m8 16 1.5-1.5" />
      <path d="M14.5 9.5 16 8" />
      <path d="m8 8 1.5" />
      <path d="M14.5 14.5 16" />
    </svg>
  )
}


function CropIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 2v14a2 2 0 2h14" />
      <path d="M18 22V8a2 2 0 0-2-2H2" />
    </svg>
  )
}
